TimeEntry/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace TimeEntry.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime DateOfBirth  { get; set; }


    }
}

TimeEntry/Models/ErrorViewModel.cs
namespace TimeEntry.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TimeEntry/Models/Manager.cs
using System.ComponentModel.DataAnnotations;

namespace TimeEntry.Models
{
    public class Manager 
    {
        [Key]
        public int Id { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

TimeEntry/Models/TimeSheetEntry.cs
using System.ComponentModel.DataAnnotations;
using TimeEntry.Data.Enums;

namespace TimeEntry.Models
{
    public class TimeSheetEntry
    {
        [Key]
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }

        [Required(ErrorMessage ="Please enter Work Date")]
        public DateTime WorkDate { get; set; }
        public DateTime SubmitDate { get; set; }
        
        [Required(ErrorMessage ="Please enter start time")]
        public DateTime StartTime { get; set; }
        
        [Required(ErrorMessage ="Please enter end time")]
        public DateTime EndTime { get; set; }
        
        [Required(ErrorMessage ="Please select workorder")]
        public WorkOrder WorkOrder { get; set; }
        public int ManagerId { get; set; }
        public bool Approved { get; set; }

    }
}

TimeEntry/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using TimeEntry.Data;
using TimeEntry.Models;

namespace TimeEntry.Controllers
{
    public class EmployeeController : Controller
    {
        private AppDbContext _appDbContext;
        public EmployeeController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            var employees = _appDbContext.Employees.ToList();
            return View(employees);
        }
        public IActionResult EnterTime()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EnterTime(TimeSheetEntry timeEntry)
        {
            if (!ModelState.IsValid)
            {
                return View(timeEntry);
            }
            timeEntry.SubmitDate = DateTime.Now;
            timeEntry.Approved = false;
            timeEntry.EmployeeId = 1;
            timeEntry.EmployeeName = _appDbContext.Employees?.ToList().FirstOrDefault(c => c.Id == timeEntry.EmployeeId).FullName;

            await _appDbContext.AddAsync(timeEntry);

            await _appDbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


    }
}

TimeEntry/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TimeEntry.Models;

namespace TimeEntry.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TimeEntry/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using TimeEntry.Data;
using TimeEntry.Models;

namespace TimeEntry.Controllers
{
    public class ManagerController : Controller
    {
        private AppDbContext _appDbContext;
        public ManagerController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IActionResult Index()
        {
            var employees = _appDbContext.Managers.ToList();
            return View(employees);
        }
        public async Task<IActionResult> ApproveTime()
        {
            var timeSheetEntries = await _appDbContext.Set<TimeSheetEntry>().ToListAsync();
            return View(timeSheetEntries);
        }
        [HttpPost]
        public async Task<IActionResult> ApproveTime(List<TimeSheetEntry> timeEntries)
        {
            foreach (var timeEntry in timeEntries)
            {
                if (!ModelState.IsValid)
                {
                    return View(timeEntry);
                }


                timeEntry.SubmitDate = DateTime.Now;
                timeEntry.Approved = true;
                timeEntry.ManagerId = 1;

                EntityEntry entityEntry = _appDbContext.Entry(timeEntry);

                entityEntry.State = EntityState.Modified;

                await _appDbContext.SaveChangesAsync();
            }


            return RedirectToAction(nameof(Index));
        }
    }
}

TimeEntry/Views/Employee/EnterTime.cshtml
@using TimeEntry.Data.Enums
@model TimeSheetEntry
@{
    ViewData["Title"] = "Enter your time sheet";
}


<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Enter your time sheet</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="EnterTime">
                    <div asp-validation-summary="ModelOnly" class="text-danger">

                    </div>
                    
                    <div class="form-group">
                        <label asp-for="WorkDate" class="control-label"></label>
                        <input asp-for="WorkDate" type="date" class="form-control" />
                        <span asp-validation-for="WorkDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartTime" class="control-label"></label>
                        <input asp-for="StartTime" type="time" class="form-control" />
                        <span asp-validation-for="StartTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EndTime" class="control-label"></label>
                        <input asp-for="EndTime" type="time" class="form-control" />
                        <span asp-validation-for="EndTime" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                        <label asp-for="WorkOrder" class="control-label"></label>
                        <select asp-for="WorkOrder" class="form-control" asp-items="Html.GetEnumSelectList<WorkOrder>()"></select>
                        <span asp-validation-for="WorkOrder" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-outline-success float-right" />
                        
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

TimeEntry/Views/Employee/Index.cshtml
@model List<Employee>

@{
    ViewData["Title"] = "Enter Time";
}

<div> 
    <ul>
         @foreach(var employee in Model)
    {
        
        <li>Welcome @employee.FullName</li>
    }
    </ul>
   
    
</div>

TimeEntry/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TimeEntry/Views/Manager/ApproveTime.cshtml
@model List<TimeSheetEntry>

@{
    ViewData["Title"] = "Approve time";
}

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Employee Name
                    </th>
                    <th>
                        Employee Id
                    </th>
                    <th>
                        Work Date
                    </th>
                    <th>
                        Work Order
                    </th>
                    <th>
                        Start Time
                    </th>
                    <th>
                        End Time
                    </th>

                    <th>
                        Approve
                    </th>


                </tr>
            </thead>
            <tbody>
                @foreach (var entry in Model)
                {
                    <tr>
                        <td>
                            @entry.EmployeeName
                        </td>
                        <td>
                            @entry.EmployeeId
                        </td>
                        <td>
                            @entry.WorkDate
                        </td>
                        <td>
                            @entry.WorkOrder
                        </td>
                        <td>
                            @entry.StartTime
                        </td>
                        <td>
                            @entry.EndTime
                        </td>

                        <td>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

TimeEntry/Views/Manager/Index.cshtml
@model List<Manager>

@{
    ViewData["Title"] = "Managers";
}

<div> 
    <ul>
         @foreach(var manager in Model)
    {
        
        <li>Welcome @manager.FullName</li>
    }
    </ul>
   
    
</div>

TimeEntry/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimeEntry</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TimeEntry.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TimeEntry</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EnterTime">Enter Time</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="ApproveTime">Approve Time</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TimeEntry - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>